### ISSUE TITLE
Kubernetes Service Catalog interop : idempotent on duplicate create service

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/osb-cmdb-spike#17]
### Expected behavior

Expecting Openshift service catalog to be able to consume services fronted by OSBCMDB.

### Observed behavior
Openshift issues multiple PUT to create a service instance. Seems compliant with OSB spec.

.https://github.com/kubernetes-sigs/service-catalog/issues/1639

The broker rejects the duplicate PUT, giving provisionning error on OpenShift v3.9.51 ( Kubernetes v1.9.1+a0ce1bc657 )

cc @pdechamboux

**Comment by gberche-orange** [comment]
Symptom when concurrent provisionning request is sent by K8S

```
   2020-02-20T17:28:00.44+0100 [APP/PROC/WEB/0] OUT org.cloudfoundry.client.v2.ClientV2Exception: CF-ServiceInstanceNameTaken(60002): The service instance name is taken: 95a4a8e5-52df-4810-82f0-d04366efbd5c
   2020-02-20T17:28:00.44+0100 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$0(ErrorPayloadMapper.java:46) ~[cloudfoundry-client-reactor-3.16.0.RELEASE.jar!/:na]
   2020-02-20T17:28:00.44+0100 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$9(ErrorPayloadMapper.java:98) ~[cloudfoundry-client-reactor-3.16.0.RELEASE.jar!/:na]
   2020-02-20T17:28:00.44+0100 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
   2020-02-20T17:28:00.44+0100 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
   2020-02-20T17:28:00.44+0100 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEA
```

**Comment by gberche-orange** [comment]
Desired approach:
* if there is a provisioning in progress with same id then
   * look up the service instance's  plan/service/params / status
   * if not same, return 409 (conflict)
   * otherwise return 202 accepted
* otherwise
   * look up the service instance's plan/service/params / status
   * if not same, return 409 (conflict)
   * otherwise return 200

This is costly to do because the StateRepository is not currently accessible to CloudFoundryDeployer but only the WorkflowServiceInstanceService

Alternative more affordable degraded approach
* if there is a provisioning in progress with same id then
   * return 202 accepted
* otherwise try create a new service instance
   * if creation fails due to existing service instance return 200 OK
   * if creation fails due to other error fails
   * otherwise return 202 accepted

=> we sacrifice the cases where 
* a custom OSB client is submitting duplicate requests and will receive 202 accepted instead of 409 conflict or 200 OK

**Comment by gberche-orange** [comment]
Pb with initial implementation in https://github.com/orange-cloudfoundry/osb-cmdb-spike/pull/27/commits/ec163e71aa20cc0eaaad570c87cbb1392d93b909: race condition between servlet threads (reading the state repository) and reactor threads (writing to state repository async)

Alternatives:
* move the state repository write to the servlet thread
* don't use service instance state repository

**Comment by gberche-orange** [comment]
Same problem arises with service bindings:
* openshift creates dup service binding requests
* osb-cmdb successfully returns the 1st service binding with a 200 and credentials
* osb-cmdb fails to create a duplicate service key, polutes logs and fails with a 500 error
* openshift returns a sucessful service binding.

```
org.cloudfoundry.client.v2.ClientV2Exception: CF-ServiceKeyNameTaken(360001): The service key name is taken: a6c72b10-9749-4395-b257-bfab24c49d53
```

Log pollution of level ERROR:

```
19:02:33.230: [APP/PROC/WEB.0] 2020-02-26 18:02:33.229 ERROR 27 --- [ry-client-nio-3] o.s.c.appbroker.deployer.DeployerClient  : Error creating backing service key a6c72b10-9749-4395-b257-bfab24c49d53 for service 6a9aac92-a6e4-4141-a1c9-15dc0cf577bb with error 'CF-ServiceKeyNameTaken(360001): The service key name is taken: a6c72b10-9749-4395-b257-bfab24c49d53'
[...]
19:02:33.238: [APP/PROC/WEB.0] 2020-02-26 18:02:33.235 ERROR 27 --- [ry-client-nio-3] d.DefaultBackingServicesProvisionService : Error creating backing services keys [BackingServiceKey{serviceInstanceName='6a9aac92-a6e4-4141-a1c9-15dc0cf577bb', name='a6c72b10-9749-4395-b257-bfab24c49d53', plan='null', parameters={}, properties={keepTargetSpaceOnDelete=true, target=p-mysql}, parametersTransformers=[], rebindOnUpdate=false}] with error 'CF-ServiceKeyNameTaken(360001): The service key name is taken: a6c72b10-9749-4395-b257-bfab24c49d53'

19:02:33.238: [APP/PROC/WEB.0] 2020-02-26 18:02:33.237 ERROR 27 --- [ry-client-nio-3] ppDeploymentCreateServiceBindingWorkflow : Error creating backing services keysfor p-mysql/10mb with error 'CF-ServiceKeyNameTaken(360001): The service key name is taken: a6c72b10-9749-4395-b257-bfab24c49d53'

19:02:33.245: [APP/PROC/WEB.0] 2020-02-26 18:02:33.244 ERROR 27 --- [ry-client-nio-3] s.c.ServiceBrokerWebFluxExceptionHandler : Unknown exception handled: 
``` 
The service binding specs mentions at https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#binding in the [response-6 section](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-6):

> Status Code | Description
> -- | --
> 200 OK | SHOULD be returned if the Service Binding already exists and the  requested parameters are identical to the existing Service Binding. The  expected response body is below.
> 201 Created | MUST be returned if the Service Binding was created as a result of this request. The expected response body is below.
> 202 Accepted | MUST be returned if the binding is in progress. The operation string MUST match that returned for the original request. This triggers the Platform to poll the Polling Last Operation for Service Bindings  endpoint for operation status. Information regarding the Service  Binding (i.e. credentials) MUST NOT be returned in this response. Note  that a re-sent PUT request MUST return a 202 Accepted, not a 200 OK, if the Service Binding is not yet fully created.

However, the osb-cmdb service binding are not yet asynchronous (nor is there a scab support for async service bindings), hence returning a 202 for dup binding requests isn't an option.

Possible alternatives:




1. Keep returning a 500 error and try to reduce log pollution 
   1.  Avoid creating duplicate service keys using the state repository to detect inflight requests
      1.  throw a [ServiceBrokerException](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/a8fa63fdfcbf0f2f6e103ae1f9082ff3c59e7a90/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerExceptionHandler.java#L241-L245) with a helpful diagnostic message
   1.  Just add error handling for `org.cloudfoundry.client.v2.ClientV2Exception: CF-ServiceKeyNameTaken(360001)`
1.  Keep returning a 500 error and ignore log pollution

**Comment by gberche-orange** [comment]
Pointers and procedure to refresh service catalog in Openshift:
* install openshift cli (orange onprem offer doc)
* from openshift portal, copy connection command (generates an auth token)
* login into openshift cli oc 
* install svcat cli https://svc-cat.io/docs/install/#installing-the-service-catalog-cli for [linux](https://svc-cat.io/docs/install/#linux)
* activate autocompletion `svcat completion --help`

**Comment by gberche-orange** [comment]
Started an upstream PR in https://github.com/spring-cloud/spring-cloud-app-broker/pull/343 but there is remaining effort needed to diagnose test failure. Pausing for now as I'm out of budget for this upstream PR.

![image](https://user-images.githubusercontent.com/4748380/76218511-a4161500-6214-11ea-9174-464b95c72d68.png)
